services:
  db:
    image: postgres:16
    container_name: pediatric_system_db_container
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pediatric_system_db

    ports:
      - "5434:5432"

    volumes:
      - dbdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pediatric_system_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
